/*
 * Created on 24-Nov-2003 at 14:44:40
 */
package de.enough.doc2java;


import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;


/**
 * models the data of a class.
 */
class ClassModel {
	private boolean isInterface;
	private String className;
	private String classDefinition;
	private String packageName;
	private JavaDocComment classComments;
	private ArrayList variables;
	private ArrayList generatedVariables;
	private HashMap generatedVariablesByName;
	private ArrayList constructors;
	private ArrayList methods;
	
	public ClassModel(  String className, String classDefinition, String packageName, boolean isInterface ) {
		this.className = className;
		this.classDefinition = classDefinition; 			
		this.packageName = packageName;
		this.isInterface = isInterface;
	}
	
	public void setClassName( String className ) {
		this.className = className;
	}
	
	public void setPackageName( String packageName ) {
		this.packageName = packageName;
	}
	
	public void setClassComments( JavaDocComment comment ) {
		this.classComments = comment;
	}
	
	public void addVariable( Variable variable ) {
		if (this.variables == null) {
			this.variables = new ArrayList();
		}
		this.variables.add( variable );
	}

	public void addConstructor( Method method ) {
		if (this.constructors == null) {
			this.constructors = new ArrayList();
		}
		this.constructors.add( method );
	}
	
	
	public void addMethod( Method method ) {
		if (this.methods == null) {
			this.methods = new ArrayList();
		}
		this.methods.add( method );
	}

	/**
	 * Adds a variable which is defined by a setter or by a getter-method.
	 * 
	 * @param fieldName name of the variable.
	 * @param fieldType type of the variable.
	 */
	public void addGeneratedVariable(String fieldName, String fieldType) {
		if ( this.generatedVariablesByName == null) {
			this.generatedVariablesByName = new HashMap();
			this.generatedVariables = new ArrayList();
		}
		if (this.generatedVariablesByName.get( fieldName ) == null) {
			this.generatedVariablesByName.put( fieldName, Boolean.TRUE );
			this.generatedVariables.add( "\tprivate " + fieldType + " " + fieldName + ";");
		}
	}
	
	
	public String[] toStringArray() {
		ArrayList lines = new ArrayList();
		lines.add( "// generated by de.enough.doc2java.Doc2Java (www.enough.de) on " + new Date() );
		if (this.packageName != null) {
			lines.add( "package " + this.packageName + ';');
		}
		lines.add( "" );
		if (this.classComments != null) {
			String[] comments = this.classComments.toStringArray( 0 );
			for (int i = 0; i < comments.length; i++) {
				lines.add( comments[i] );
			}
		}
		lines.add( this.classDefinition );
		lines.add( "{" );
		addLines(this.variables,  lines );
		ArrayList tailingList = new ArrayList();
		addLines(this.constructors,  tailingList );
		addLines(this.methods,  tailingList );
		if (this.generatedVariables != null) {
			lines.add( "\t//following variables are implicitely defined by getter- or setter-methods:");
			lines.addAll( this.generatedVariables );
			lines.add( "" );
		}
		lines.addAll( tailingList );
		lines.add( "}");
		return (String[]) lines.toArray( new String[ lines.size() ]);
	}

	private void addLines(ArrayList source, ArrayList lines) {
		if (source != null) {
			for (int i = 0; i < source.size(); i++ ) {
				Object object = source.get( i );	
				String[] innerLines = null;
				if (object instanceof Variable) {
					innerLines = ( (Variable) object).toStringArray( 1 );
				} else {
					innerLines = ( (Method) object).toStringArray( 1 );
				}
				for (int j = 0; j < innerLines.length; j++) {
					lines.add( innerLines[j] );
				}
				lines.add( "" );
			}
		}
	}

	public boolean isInterface() {
		return this.isInterface;
	}

	/**
	 * @return the name of the package of this class.
	 */
	public String getPackageName() {
		return this.packageName;
	}

	/**
	 * @return the name of the represented class.
	 */
	public String getClassName() {
		return this.className;
	}

}